services:
  postgres:
    image: postgres:16-alpine
    container_name: koffee-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-koffee_auth}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-koffee} -d ${POSTGRES_DB:-koffee_auth}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
